### PR TITLE
Add drone-openfaas plugin

### PR DESCRIPTION
**Pull request by bibarrav**
Hi, I want to publish an OpenFaaS plugin for Drone.io.

### CODE REVIEW

**Comment by pbaezab** [comment]
+1

**Comment by tboerger** [comment]
Generally the examples part doesn't follow the style as all the other plugins :-1:

**Comment by bibarrav** [comment]
I'm updated the example with a simple one.

**Comment by bibarrav** [comment]
And added openfaas logo too.

**Comment by bibarrav** [comment]
@tboerger can you review the updated example? THX

**Pull request merged**
