### PR TITLE
Fix build errors while using rel shortcode

### PR DESCRIPTION
**Pull request by xoxys**

### CODE REVIEW

**Comment by xoxys** [comment]
Fix for https://github.com/drone/drone-plugin-index/issues/196

**Comment by tboerger** [comment]
Please also revert the `pull: true`, I know that brad wants to avoid the usage of it :)

**Comment by xoxys** [comment]
Done. Maybe we should enable drone for pull requests to find those errors before merge?

**Comment by tboerger** [comment]
@bradrydzewski also happy with that?

**Comment by remorses** [comment]
Please merge

**Pull request merged**
