### PR TITLE
Added cbrgm/drone-hugo plugin

### PR DESCRIPTION
**Pull request by cbrgm**
Hi there!

Because I learned to love Drone.io, I wrote a plugin for the website generator Hugo to make publishing static generated websites easier.

The plugin encapsulates the most important settings for Hugo, is lightweight and flexible. All important parameters can be conveniently defined via the .drone.yml.

Hugo Drone Plugin: https://github.com/cbrgm/drone-hugo
Hugo: https://github.com/gohugoio/hugo

Please do not hesitate to contact me if you have any questions.

Cheers

### CODE REVIEW

**Comment by cbrgm** [comment]
Ping

**Comment by bradrydzewski** [comment]
sorry for the delay, merging now. Great blob post, by the way!

**Comment by cbrgm** [comment]
Awesome! Thanks a lot! :smile:

**Comment by metalmatze** [comment]
Thanks for the plugin. Found you blog post by accident when googling for `drone hugo`. 3 days after you published. Good SEO, I guess. :blush: 

It's already in production use for one of my projects: :+1: 
https://github.com/CloudNativeCasts/website/blob/master/.drone.yml#L3

**Comment by cbrgm** [comment]
Thank you for your feedback @metalmatze ! I'm very happy to see that! :Smile: CloudNativeCasts looks like an exciting project!

**Pull request merged**
