### PR TITLE
Add matrix plugin

### PR DESCRIPTION
**Pull request by ptman**

### CODE REVIEW

**Comment by tboerger** [comment]
Can you please add a separate paragraph for the available secrets?

**Comment by ptman** [comment]
Sure. Is this good?

**Comment by ptman** [comment]
I tried looking for a matrix icon, but I couldn't find one. I'll keep looking.

**Comment by ptman** [comment]
ok, found logo by asking around

**Comment by tboerger** [comment]
Docs are published at http://plugins.drone.io/ptman/drone-plugin-matrix/ now.

**Comment by ptman** [comment]
Thank you!

**Pull request merged**
