### PR TITLE
Move docs to drone-pypi and fix 1.0 syntax

### PR DESCRIPTION
**Pull request by xoxys**
@tboerger Fixed docs to match https://github.com/drone-plugins/drone-pypi/pull/16

### CODE REVIEW

**Comment by tboerger** [comment]
I guess renaming it is wrong as the other plugin is still available.

**Comment by xoxys** [comment]
So we should keep both pypi plugins in index?

**Comment by xoxys** [comment]
This Plugin is based on the work of @gjtempleton and from what I am understood he was fine with the pick up and moving it forward https://github.com/drone-plugins/drone-pypi/issues/14#issuecomment-438043269

I think two PyPi plugins doing nearly the same can be confusing. But sure, I can revert this changes if you like so :)

**Comment by gjtempleton** [comment]
@tboerger I'm happy with this, it's an improvement on the plugin I created, and from what I've seen provides all the functionality mine does, with improvements.

As @xoxys says, merging this reduces confusion.

Great work on getting this over the line btw @xoxys 🙇

**Pull request merged**
