### PR TITLE
Drone Rocket.Chat Plugin sends the build status notifications over rocket.chat.

### PR DESCRIPTION
**Pull request by alexgamas**

### CODE REVIEW

**Comment by tboerger** [comment]
You have built a dedicated plugin for rocket.chat? The official slack plugin already works pretty fine for rocket.chat :)

**Comment by alexgamas** [comment]
thanks, i did not know.

**Comment by bradrydzewski** [comment]
You should add a secrets section (similar to http://plugins.drone.io/drone-plugins/drone-docker/#secret-reference)

**Comment by tboerger** [comment]
Any update?

**Comment by d1wilko** [comment]
Hi,

We have recently updated the drone plugin index and docs are no longer written in markdown - they are now a more consistent yaml format e.g. [docker](https://github.com/drone/drone-plugin-index/blob/master/plugins/docker/content.yaml)

Please have a look at the new readme if you would like to run the new plugin index [readme](https://github.com/drone/drone-plugin-index/blob/master/README.md)

If you would still like to add documentation to the plugins index can you change the format to
- An individual folder per plugin inside the `plugins` folder
- a `content.yaml` file that follows the format in the example above - this is for quick discovery, not full documentation
- an `original.md` file that can contain the markdown you have already written
- a logo image inside the `public/logos` folder

Thanks :)

**Pull request closed without merging**
