### PR TITLE
Adds build.deployTo to the drone-slack documentation. This was added …

### PR DESCRIPTION
**Pull request by ace03uec**
…in PR https://github.com/drone-plugins/drone-slack/pull/55 for drone-slack.

### CODE REVIEW

**Comment by donny-dont** [comment]
@tboerger just a general comment as this PR is fine but it got me wondering should there just be a document on the template functionality for notification plugins that should just be referenced?

**Comment by tboerger** [comment]
@donny-dont yeah there had been some discussion some time ago to add the templating docs to the drone documentation and link to it from all plugins that implement that.

**Comment by ace03uec** [comment]
@tboerger : More documentation around templating would be great. If there's a link to the discussion would love to see what was discussed.

**Comment by tboerger** [comment]
I don't have a link to that discussion, I think that happened on the chat.

**Comment by ace03uec** [comment]
@tboerger @donny-dont : Would any changes be required for this PR ?

**Comment by tonglil** [comment]
Sorry merged before I saw there were no other approvals.

**Pull request merged**
