### PR TITLE
Drone WeChat Work Plugin

### PR DESCRIPTION
**Pull request by clem109**
The previous WeChat for Work plugin was transmitting user secrets to a 3rd party service https://sc.ftqq.com rather than directly to the WeChat servers which could result in users credentials being stolen.

### CODE REVIEW

**Comment by clem109** [comment]
Cool my first merged pull request to open source, feels good 😄

**Comment by tboerger** [comment]
I just want to mention, the other wechat plugin directly mentions which service gets involved:

> You can config your own wechat corp id, or you can get wechat notification quickly with key from ServerChan. If you use ServerChan you need get SCKEY before using.

I can not read or speak chinese, so I don't know if this is a trusted service or not, but so far it looks pretty unfair to me that the other service just gets dropped from the plugin index. Maybe @appleboy or @tonglil can shed some light on it for me?

**Comment by appleboy** [comment]
This is a third-party service, right? @clem109

**Comment by clem109** [comment]
This is what my Chinese colleagues told me, thats why I submitted the pull request. They said it was risky using that plugin. ServerChan is a third party service, it's not a part of WeChat.  @appleboy

**Comment by appleboy** [comment]
@clem109 @tboerger maybe we should remove the previous drone-wechat plugin we merged before #82 

What do you think?

cc @tonglil

**Comment by tboerger** [comment]
@appleboy @clem109 already dropped the plugin from @lizheming, that's why i said this looks unfair to me.

**Comment by tonglil** [comment]
We can restore the previous plugin as `ServerChan WeChat` and have both in the index?

So my understanding of ServerChan is a WeChat compatible protocol server service that sets up WeChat numbers so that users do not have to apply for them through WeChat themselves (of course there are limitations, eg message quotas etc). As a result, the previous plugin could communicates with ServerChan to send messages to WeChat destinations.

This is through my elementary level of Chinese and brief look at the code of the previous plugin.

**Comment by lizheming** [comment]
As #82 pr said, serverchan just an downgrade option for user. And it's important I have not guide users to use serverchan service. It's just another choice for them, they can use wechat work config directly. So I don't agree with remove dicision just because this plugin have the same function. 

Thank you @tonglil for long words, but I also can't agree with change my plugin name. Because I have used in some projects, name change will confuse me. If all of you still puzzle by serverchan service option, I will removed it from my plugin.

**Comment by lizheming** [comment]
And does @bradrydzewski notice there has an delete commit that delete my plugin in this pr? I can't believe you agree with remove my plugin wildly in repo without my agreement. Even I don't know it before merged. I think it's very discourteousness in open source.

**Comment by clem109** [comment]
I'm happy for @lizheming to have his plugin restored, I was going by what my colleagues were telling me. If they were mistaken then I apologise 😅

**Comment by tboerger** [comment]
So please add the other plugin back again :)

**Comment by clem109** [comment]
@lizheming 真抱歉，我的同事告诉我你的package恶毒. 他们错了。 

@tboerger @appleboy @tonglil I reverted my pull request 😃

**Comment by lizheming** [comment]
@clem109 It doesn't matter. We should let everyone know the truth. In the final analysis it's all my fault that add this unnecessary option. I just think severchan service (not mine project) is convenience for user so I add it. and If you can see my plugin code(I think you also can watch some nodejs code), you can clear for that.

By the way "恶毒" is always describe people is a bad guy, I think it's suitable for using "恶意" in here. 😺

**Comment by appleboy** [comment]
@clem109 @lizheming We can provide multiple same plugins. Just rename the origin plugin and add more description.

**Comment by clem109** [comment]
@appleboy okay cool 👍 I'm working on a rocket-chat plugin too so expect a pull request in the coming days 😄

**Comment by lizheming** [comment]
@appleboy I think if you have plugin name doubt you can mention in #82 before it merged, I will cooperate with you gladly just like #82 did. Serverchan service just a downgrade function. It's not necessary for my plugin, so it seems that change name because of sub function without reason. I have removed serverchan service option, and when I want to update my plugin description, I found it's already removed in this pr.

**Comment by tboerger** [comment]
@clem109 the slack plugin works totally fine with rocket.chat, using that all the time.

**Comment by tonglil** [comment]
Sorry folks, was OOO and didn't catch up to this.
I am glad to see both plugins in the index.
Once again, apologies for the mixup and will seek to get input from all authors in the future when considering to de-list a plugin.

**Pull request merged**
