### PR TITLE
add drone-cloudfoundry plugin

### PR DESCRIPTION
**Pull request by cheslip**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
awesome, thanks!

**Comment by bradrydzewski** [comment]
hey, qq, it looks like repository [Comcast/drone-cloudfoundry](https://github.com/Comcast/drone-cloudfoundry) is private. Is it possible to make this public? Generally speaking we only publish open source plugins to registry so that developers can inspect the source of the plugins they use

**Comment by cheslip** [comment]
after a conversation on gitter the repo was actually deleted so ownership of drone-plugins/drone-cloudfoundry could be transferred. Does that work?

**Comment by bradrydzewski** [comment]
oh, one minor change. The directory structure is based on the github repository name. So it should be `content/Comcast/drone-cloudfoundry/index.md` at this time. Thanks!

**Comment by bradrydzewski** [comment]
thanks!

**Pull request merged**
